# Generated by Django 5.0.1 on 2024-01-25 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
