# Generated by Django 5.0.1 on 2024-01-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_pomodoro'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_pomodoros',
            field=models.IntegerField(default=0),
        ),
    ]
