# Generated by Django 5.0.1 on 2024-02-03 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customuser_total_pomodoros'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodoro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
