# Generated by Django 5.0.1 on 2024-02-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_pomodoro_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost_in_pomodoros', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='virtual_currency_earned',
            field=models.IntegerField(default=0),
        ),
    ]
