# Generated by Django 5.0.1 on 2024-02-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_product_pomodoro_virtual_currency_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('luxury_cars', 'Luxury Cars'), ('high_end_watches', 'High-end Watches'), ('fine_jewelry', 'Fine Jewelry'), ('luxury_real_estate', 'Luxury Real Estate'), ('private_jets_and_yachts', 'Private Jets'), ('yachts', 'Yachts'), ('art_and_collectibles', 'Art and Collectibles'), ('exotic_vacations', 'Exotic Vacations')], default='Uncategorized', max_length=100),
        ),
    ]
