# Generated by Django 5.0.1 on 2024-02-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('luxury_cars', 'Luxury Cars'), ('high_end_watches', 'High-end Watches'), ('fine_jewelry', 'Fine Jewelry'), ('luxury_real_estate', 'Luxury Real Estate'), ('private_jets', 'Private Jets'), ('yachts', 'Yachts'), ('art_and_collectibles', 'Art and Collectibles'), ('exotic_vacations', 'Exotic Vacations')], default='Uncategorized', max_length=100),
        ),
    ]
