# Generated by Django 5.0.1 on 2024-02-06 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchased_by',
            field=models.ManyToManyField(blank=True, related_name='purchased_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
