# Generated by Django 5.0.1 on 2024-02-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_product_purchased_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_in_virtual_currency',
            field=models.IntegerField(default=0),
        ),
    ]
