# Generated by Django 5.0.1 on 2024-02-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_product_cost_in_virtual_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='virtual_currency_balance',
            field=models.IntegerField(default=0),
        ),
    ]
