# Generated by Django 5.0.1 on 2024-02-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_customuser_virtual_currency_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('high_end_watches', 'High-end Watches'), ('luxury_cars', 'Luxury Cars'), ('fine_jewelry', 'Fine Jewelry'), ('luxury_real_estate', 'Luxury Real Estate'), ('private_jets', 'Private Jets'), ('yachts', 'Yachts'), ('art_and_collectibles', 'Art and Collectibles'), ('exotic_vacations', 'Exotic Vacations')], default='Uncategorized', max_length=100),
        ),
    ]
