# Generated by Django 5.0.1 on 2024-02-09 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodoro',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('watches', 'High-end Watches'), ('luxury cars', 'Luxury Cars'), ('jewelry', 'Fine Jewelry'), ('real estate', 'Luxury Real Estate'), ('private jets', 'Private Jets'), ('yachts', 'Yachts'), ('art and collectibles', 'Art and Collectibles'), ('exotic vacations', 'Exotic Vacations')], default='Uncategorized', max_length=100),
        ),
    ]
