# Generated by Django 5.0.1 on 2024-02-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_pomodoro_user_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('watches', 'High-end Watches'), ('Cars', 'Luxury Cars'), ('jewelry', 'Fine Jewelry'), ('real_estate', 'Luxury Real Estate'), ('private_jets', 'Private Jets'), ('yachts', 'Yachts'), ('art_and_collectibles', 'Art and Collectibles'), ('exotic_vacations', 'Exotic Vacations')], default='Uncategorized', max_length=100),
        ),
    ]
