# Generated by Django 5.0.1 on 2024-02-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social_media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
