# Generated by Django 5.0.1 on 2024-03-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_customuser_social_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='college_or_workplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='future_goal',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('ca_cs', 'CA/CS'), ('lawyer', 'Lawyer'), ('teacher', 'Teacher'), ('architect', 'Architect'), ('mba', 'MBA'), ('civil_servant', 'Civil Servant'), ('fashion_designer', 'Fashion Designer'), ('software_engineer', 'Software Engineer'), ('graphic_designer', 'Graphic Designer'), ('marketing_professional', 'Marketing Professional'), ('content_writer', 'Content Writer'), ('jee', 'JEE'), ('neet', 'NEET'), ('cuet', 'CUET'), ('gate', 'GATE'), ('cat', 'CAT'), ('nid_dat', 'NID DAT'), ('ugc_net', 'UGC NET'), ('upsc', 'UPSC'), ('ssc', 'SSC'), ('nda', 'NDA'), ('clat', 'CLAT'), ('ailet', 'AILET'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='other_goal_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
