# Generated by Django 5.0.1 on 2024-03-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_customuser_age_customuser_college_or_workplace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
